version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: always

  app:
    build:
      context: ../
      dockerfile: config/dockerfile
    container_name: app
    ports:
      - "8000:80"
    volumes:
      - ../app:/app
    environment:
      RABBIT_URL: amqp://guest:guest@rabbitmq:5672/
      QUEUE_ENTRADA: fila.notificacao.entrada.lucas
      QUEUE_RETRY:   fila.notificacao.retry.lucas
      QUEUE_VALID:   fila.notificacao.validacao.lucas
      QUEUE_DLQ:     fila.notificacao.dlq.lucas
      PREFETCH: "10"
    depends_on:
      - rabbitmq
    restart: unless-stopped
