FROM python:3.12

WORKDIR /app

RUN pip install poetry

COPY ./app /app

COPY config/pyproject.toml /app/pyproject.toml
RUN poetry config virtualenvs.create false

RUN poetry install --no-root

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80", "--reload"]
